<a href="https://colab.research.google.com/github/mkodk/LectDM/blob/main/discrete_math13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("hello, world")

x = 3
print("정수 : %01d, %02d, %03d, %04d, %05d"%(x,x,x,x,x))

x = 256.123
print("실수 : %.0f, %.1f, %.2f"%(x,x,x))

x = "hello world"
print("문자열 : [%s]"%(x))

hello, world
정수 : 3, 03, 003, 0003, 00003
실수 : 256, 256.1, 256.12
문자열 : [hello world]


In [3]:
contents = ["regression","classifcation","sym","clustering","dimension reduction","nn","cnn","ae","gan","rnn"]

for con in contents:
  if con in ["regression","classifcation","sym","clustering","dimension reduction"]:
    print("%s 은(는) 기계학습 입니다."%con)
  elif con in ["cnn"]:
    print("%s 은(는) convolutional neural network 입니다."%con)
  else:
    print("%s 은(는) 심츰학습 내용입니다."%con)

regression 은(는) 기계학습 입니다.
classifcation 은(는) 기계학습 입니다.
sym 은(는) 기계학습 입니다.
clustering 은(는) 기계학습 입니다.
dimension reduction 은(는) 기계학습 입니다.
nn 은(는) 심츰학습 내용입니다.
cnn 은(는) convolutional neural network 입니다.
ae 은(는) 심츰학습 내용입니다.
gan 은(는) 심츰학습 내용입니다.
rnn 은(는) 심츰학습 내용입니다.


In [4]:
for (i,con) in enumerate(contents):
  print("[%d/%d]: %s"%(i,len(contents),con))

[0/10]: regression
[1/10]: classifcation
[2/10]: sym
[3/10]: clustering
[4/10]: dimension reduction
[5/10]: nn
[6/10]: cnn
[7/10]: ae
[8/10]: gan
[9/10]: rnn


In [5]:
def sum(a,b):
  return a+b

x = 10.0
y = 20.0

print(f"{x} + {y} = {x+y}")

10.0 + 20.0 = 30.0


In [7]:
a = []
b = [1,2,3]
c = ["hello",",","world"]
d = [1,2,3,"x","y","z"]
x = []

print(x)

x.append('a')
print(x)

x.append(123)
print(x)

x.append(["a","b"])
print(x)

[]
['a']
['a', 123]
['a', 123, ['a', 'b']]


In [8]:
dic = dict()
dic["name"] = "ch"
dic["town"] = "osan"
dic["job"] = "backsu"
print(dic)

{'name': 'ch', 'town': 'osan', 'job': 'backsu'}


In [9]:
import numpy as np

In [10]:
def print_val(x):
  print(f"type : {type(x)}")
  print(f"shape : {x.shape}")
  print(f"값 : \n{x}")
  print(" ")

In [11]:
x = np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)

type : <class 'numpy.ndarray'>
shape : (3,)
값 : 
[1 2 3]
 
type : <class 'numpy.ndarray'>
shape : (3,)
값 : 
[5 2 3]
 


In [12]:
y = np.array([[1,2,3],[4,5,6]])
print_val(y)

a = np.zeros((2,2))
print_val(a)

a = np.ones((3,2))
print_val(a)

a = np.eye(3,3)
print_val(a)

type : <class 'numpy.ndarray'>
shape : (2, 3)
값 : 
[[1 2 3]
 [4 5 6]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[0. 0.]
 [0. 0.]]
 
type : <class 'numpy.ndarray'>
shape : (3, 2)
값 : 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
 
type : <class 'numpy.ndarray'>
shape : (3, 3)
값 : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


In [13]:
a = np.random.random((4,4))
print_val(a)

a = np.random.randn(4,4)
print_val(a)

type : <class 'numpy.ndarray'>
shape : (4, 4)
값 : 
[[0.94388017 0.11278912 0.97278158 0.55489788]
 [0.27249128 0.73182521 0.57172898 0.79949131]
 [0.18069271 0.38686029 0.90242032 0.72202692]
 [0.43871773 0.68997687 0.34872335 0.23318572]]
 
type : <class 'numpy.ndarray'>
shape : (4, 4)
값 : 
[[ 0.36916696 -1.54232586 -0.30779679 -0.0604068 ]
 [ 0.36472621 -1.21204206  1.38547721  1.09144631]
 [ 0.21906099 -0.15834927  1.52421476 -1.49289638]
 [-1.26182827  0.1319841   1.11859511  0.94100511]]
 


In [14]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print_val(a)

b = a[:2, 1:3]
print_val(b)

row1 = a[1, :]
print_val(row1)

type : <class 'numpy.ndarray'>
shape : (3, 4)
값 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[2 3]
 [6 7]]
 
type : <class 'numpy.ndarray'>
shape : (4,)
값 : 
[5 6 7 8]
 


In [15]:
m1 = np.array([[1,2],[3,4]],dtype=np.float64)
m2 = np.array([[5,6],[7,8]],dtype=np.float64)

In [18]:
print_val(m1+m2)
print_val(np.add(m1,m2))

print_val(m1-m2)
print_val(np.subtract(m1,m2))

print_val(m1*m2)
print_val(np.multiply(m1,m2))

print_val(m1/m2)
print_val(np.divide(m1,m2))

print_val(np.sqrt(m1))

type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[ 6.  8.]
 [10. 12.]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[ 6.  8.]
 [10. 12.]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[-4. -4.]
 [-4. -4.]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[-4. -4.]
 [-4. -4.]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[ 5. 12.]
 [21. 32.]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[ 5. 12.]
 [21. 32.]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[1.         1.41421356]
 [1.73205081 2.        ]]
 


In [20]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
v1 = np.array([9,10])
v2 = np.array([11,12])

print_val(m1)
print_val(m2)
print_val(v1)
print_val(v2)

type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[1 2]
 [3 4]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[5 6]
 [7 8]]
 
type : <class 'numpy.ndarray'>
shape : (2,)
값 : 
[ 9 10]
 
type : <class 'numpy.ndarray'>
shape : (2,)
값 : 
[11 12]
 


In [21]:
print_val(v1.dot(v2))
print_val(np.dot(v1,v2))

type : <class 'numpy.int64'>
shape : ()
값 : 
219
 
type : <class 'numpy.int64'>
shape : ()
값 : 
219
 


In [22]:
print_val(m1.dot(m2))
print_val(np.dot(m1,m2))

type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[19 22]
 [43 50]]
 
type : <class 'numpy.ndarray'>
shape : (2, 2)
값 : 
[[19 22]
 [43 50]]
 


In [24]:
print_val(np.sum(m1))
print_val(np.sum(m1, axis = 0))
print_val(np.sum(m1, axis = 1))

type : <class 'numpy.int64'>
shape : ()
값 : 
10
 
type : <class 'numpy.ndarray'>
shape : (2,)
값 : 
[4 6]
 
type : <class 'numpy.ndarray'>
shape : (2,)
값 : 
[3 7]
 


In [26]:
m1 = np.array([[1,2,3],[4,5,6]])
print(m1)
print(m1.shape)

print_val(np.sum(m1))
print_val(np.sum(m1, axis = 0))
print_val(np.sum(m1, axis = 1))

[[1 2 3]
 [4 5 6]]
(2, 3)
type : <class 'numpy.int64'>
shape : ()
값 : 
21
 
type : <class 'numpy.ndarray'>
shape : (3,)
값 : 
[5 7 9]
 
type : <class 'numpy.ndarray'>
shape : (2,)
값 : 
[ 6 15]
 


In [27]:
m1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
m2 = np.zeros_like(m1)
print_val(m1)
print_val(m2)

type : <class 'numpy.ndarray'>
shape : (4, 3)
값 : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
 
type : <class 'numpy.ndarray'>
shape : (4, 3)
값 : 
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
 
